# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'letToDo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for letToDo
pod 'FirebaseAnalytics'
pod 'FirebaseAuth'
pod 'FirebaseFirestore'
pod 'SnapKit'
pod 'GoogleSignIn','5.0.2'

  target 'letToDoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'letToDoUITests' do
    # Pods for testing
  end

end
